# docker-compose is used only for development.
version: "3"

services:
  web:
    build:
      context: .
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000

  frontend:
    build: ./totalvery_react
    command: ["npm", "start"]
    volumes:
      - ./totalvery_react:/app/totalvery_react
      - node-modules:/app/totalvery_react/node_modules
    ports:
      - "3000:3000"

volumes:
  node-modules:

