# docker-compose is used only for development.
version: "3"

services:
  web:
    build:
      context: .
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
