# docker-compose is used only for development.
version: "3"

services:
  web:
    build:
      context: .
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - .:/app
    # command: python manage.py runserver
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    links:
      - my_db
  my_db:
    build: ./totalvery_db

  frontend:
    build: ./totalvery_react
    environment:
      CHOKIDAR_USEPOLLING: "true"
    command: ["npm", "start"]
    volumes:
      - ./totalvery_react:/app/totalvery_react
      - node-modules:/app/totalvery_react/node_modules
    ports:
      - "3000:3000"

volumes:
  node-modules:
