# Generated by Django 3.1.4 on 2021-01-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totalvery_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantIDs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubereatsID', models.CharField(max_length=100)),
                ('doordashID', models.CharField(max_length=100)),
                ('grubhubID', models.CharField(max_length=100)),
            ],
        ),
    ]
