# Generated by Django 3.1.5 on 2021-01-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totalvery_api', '0002_restaurantids'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubereats', models.BooleanField(default=False)),
                ('doordash', models.BooleanField(default=False)),
                ('grubhub', models.BooleanField(default=False)),
                ('ubereatsID', models.CharField(max_length=100)),
                ('doordashID', models.CharField(max_length=100)),
                ('grubhubID', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='RestaurantIDs',
        ),
    ]
