# Generated by Django 3.1.5 on 2021-01-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totalvery_api', '0003_auto_20210107_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
