# Generated by Django 3.1.5 on 2021-01-12 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totalvery_api', '0005_auto_20210111_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedetail',
            name='doordashID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='storedetail',
            name='grubhubID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='storedetail',
            name='ubereatsID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
