# Generated by Django 3.1.5 on 2021-02-04 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('totalvery_api', '0007_auto_20210124_2013'),
        ('totalvery_api', '0007_storedetail_location'),
    ]

    operations = [
    ]
