# Generated by Django 3.1.5 on 2021-02-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totalvery_api', '0008_merge_20210204_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='location',
            field=models.TextField(default=' '),
        ),
    ]
